name = "BinaryMatrixProducts"
uuid = "3ed30847-0fc3-408f-a0dc-ec55633f3837"
authors = ["erenust <erenust@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "1.11.0"
